#!/usr/bin/env bash
#
# install.sh — guided setup: configure user config, symlink the `theme`
# script and apply the default theme. Falls back to a silent copy of
# config.example.sh when run without a terminal (pipes, CI).
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEMES_DIR="$REPO_DIR/themes"
SKELETON_DIR="$REPO_DIR/skeleton"
USER_CONFIG_DIR="$HOME/.config/hypr-themes"
BIN_DIR="$HOME/.local/bin"

is_tty() { [[ -t 0 && -t 1 ]]; }

# Place one base config: copy the skeleton if the user has none, otherwise leave
# their file alone and (when it lacks the include) print how to wire it up. The
# theme only ever writes the generated partials, never these base files.
#   $1 skeleton-relative path   $2 target path
#   $3 string proving the include is present ('' = none needed)   $4 how-to hint
place_skeleton() {
    local src="$SKELETON_DIR/$1" target="$2" needle="$3" hint="$4"
    mkdir -p "$(dirname "$target")"
    if [[ ! -e "$target" ]]; then
        cp "$src" "$target"
        echo "  created $target"
    elif [[ -n "$needle" ]] && ! grep -qF "$needle" "$target"; then
        echo "  NOTE: $target exists — to theme it, $hint"
    fi
}

deploy_skeletons() {
    : "${HYPR_CONFIG_DIR:=$HOME/.config/hypr}"
    : "${WOFI_CONFIG_DIR:=$HOME/.config/wofi}"
    : "${DUNST_CONFIG_DIR:=$HOME/.config/dunst}"
    echo "Base configs (yours — never overwritten):"
    place_skeleton hypr/modules/config.lua "$HYPR_CONFIG_DIR/modules/config.lua" \
        'require("modules/theme")' \
        'add  local theme = require("modules/theme")  and use theme.border_1/border_2/border_angle/glow'
    # shellcheck disable=SC2016  # $lock_* are literal hyprlock var names shown to the user
    place_skeleton hypr/hyprlock.conf "$HYPR_CONFIG_DIR/hyprlock.conf" \
        'hyprlock-theme.conf' \
        'add  source = ~/.config/hypr/hyprlock-theme.conf  and use $lock_bg/$lock_text/$lock_accent/...'
    # wofi needs special handling: GTK loads the CSS as a data blob with no base
    # dir, so the @import must be absolute. Bake this machine's path in on copy.
    local wofi_css="$WOFI_CONFIG_DIR/style.css" colors_abs="$WOFI_CONFIG_DIR/colors.css"
    mkdir -p "$WOFI_CONFIG_DIR"
    if [[ ! -e "$wofi_css" ]]; then
        sed "s|@COLORS_CSS@|$colors_abs|" "$SKELETON_DIR/wofi/style.css" > "$wofi_css"
        echo "  created $wofi_css"
    elif ! grep -qF "colors.css" "$wofi_css"; then
        echo "  NOTE: $wofi_css exists — to theme it, add  @import url(\"$colors_abs\");  (absolute path required) and use @bg_base/@accent/@fg_text/..."
    fi
    place_skeleton dunst/dunstrc "$DUNST_CONFIG_DIR/dunstrc" \
        '' \
        'nothing to do — dunst auto-loads the dunstrc.d/ drop-in'
}

list_themes() {
    local f
    for f in "$THEMES_DIR"/*.theme; do
        [[ -e "$f" ]] && basename "$f" .theme
    done
}

count_images() {
    find "$1" -maxdepth 1 -type f \
        \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) \
        2>/dev/null | wc -l
}

write_config() {  # $1 = wallpaper dir, $2 = default theme
    cat > "$USER_CONFIG_DIR/config.sh" <<EOF
# hypr-themes user config (generated by install.sh). Edit freely.

# Where your wallpapers live; each theme references an image by name.
WALLPAPER_DIR="$1"

# Theme applied on install / first run without arguments.
DEFAULT_THEME="$2"

# Destination config dirs — override only if your configs live elsewhere.
HYPR_CONFIG_DIR="\$HOME/.config/hypr"
WOFI_CONFIG_DIR="\$HOME/.config/wofi"
DUNST_CONFIG_DIR="\$HOME/.config/dunst"
EOF
}

run_stepper() {
    echo
    echo "── hypr-themes setup ───────────────────────────────"

    # 1. Wallpapers directory
    local default_wd="$HOME/Pictures/Wallpapers" wd=""
    read -rp "Wallpapers directory [$default_wd]: " wd || true
    wd="${wd:-$default_wd}"
    wd="${wd/#\~/$HOME}"
    if [[ -d "$wd" ]]; then
        echo "  found $(count_images "$wd") image(s) there."
    else
        local mk=""
        read -rp "  '$wd' does not exist. Create it? [y/N] " mk || true
        case "${mk,,}" in
            y|yes) mkdir -p "$wd"; echo "  created $wd" ;;
            *)     echo "  note: using it anyway — add your wallpapers there later." ;;
        esac
    fi

    # 2. Default theme
    local themes=() i
    mapfile -t themes < <(list_themes)
    echo "Available themes:"
    for i in "${!themes[@]}"; do printf '  %d) %s\n' "$((i + 1))" "${themes[$i]}"; done
    local dt="" chosen="${themes[0]}"
    read -rp "Default theme [1=${themes[0]}]: " dt || true
    if [[ "$dt" =~ ^[0-9]+$ ]] && (( dt >= 1 && dt <= ${#themes[@]} )); then
        chosen="${themes[$((dt - 1))]}"
    elif [[ -n "$dt" && -f "$THEMES_DIR/$dt.theme" ]]; then
        chosen="$dt"
    fi

    write_config "$wd" "$chosen"
    echo "  wrote $USER_CONFIG_DIR/config.sh  (WALLPAPER_DIR=$wd, DEFAULT_THEME=$chosen)"
    echo "────────────────────────────────────────────────────"
}

# 1. Dependencies (delegated to the reusable checker, run before anything else)
if ! "$REPO_DIR/scripts/check-deps.sh"; then
    echo "Install the missing required dependency above, then re-run ./install.sh." >&2
    exit 1
fi

# 2. User config
mkdir -p "$USER_CONFIG_DIR"
if [[ -f "$USER_CONFIG_DIR/config.sh" ]]; then
    if is_tty; then
        ans=""
        read -rp "Existing config found. Reconfigure? [y/N] " ans || true
        case "${ans,,}" in y|yes) run_stepper ;; *) echo "Keeping existing config.sh." ;; esac
    fi
elif is_tty; then
    run_stepper
else
    cp "$REPO_DIR/config.example.sh" "$USER_CONFIG_DIR/config.sh"
    echo "Created $USER_CONFIG_DIR/config.sh from example (non-interactive)."
fi

# 3. Symlink the script
mkdir -p "$BIN_DIR"
ln -sfn "$REPO_DIR/bin/theme" "$BIN_DIR/theme"

# 4. PATH check
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo "Note: $BIN_DIR is not in PATH. Add it to your shell rc."
fi

# 5. Base configs (skeletons) — copied only when absent, never overwritten
# shellcheck source=/dev/null
source "$USER_CONFIG_DIR/config.sh"
deploy_skeletons

# 6. Apply default theme
"$REPO_DIR/bin/theme" "${DEFAULT_THEME:-peach}"

echo "hypr-themes installed. Use 'theme <name>' or 'theme' for the interactive picker."
