-- ============================================================
--  CONFIG (general, input, decoration, dwindle, misc + animations master)
-- ============================================================
-- This file is YOURS — hypr-themes never overwrites it. The colors come
-- from modules/theme.lua (regenerated by `theme <name>`); everything else
-- here (gaps, input, blur, kb_layout/kb_variant, ...) is yours to edit.

local theme = require("modules/theme")

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 16,
        border_size = 3,
        col = {
            active_border = { colors = { theme.border_1, theme.border_2 }, angle = theme.border_angle },
            inactive_border = "rgba(595959aa)",
        },
        layout = "dwindle",
        resize_on_border = true,
        allow_tearing = false,
    },

    input = {
        -- Set these to whatever your keyboard needs; hypr-themes never touches them.
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = { natural_scroll = true },
    },

    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
        },
        shadow = {
            enabled = true,
            range = 30,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- Glow (Hyprland 0.55): accent glow around the active window.
        glow = {
            enabled = true,
            color = theme.glow,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo = false,
        disable_splash_rendering = false,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        enable_swallow = false,
        focus_on_activate = true,
    },

    animations = { enabled = true },
})
